spring:
  profiles:
    active: dev 
  jpa:  
    hibernate:  
      ddl-auto: update  
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:  
    url: "jdbc:postgresql://localhost:5432/sbms"  
    username: postgres  
    password: root123
    driver-class-name: org.postgresql.Driver
